97178 limited visibiliy
jbbarth/redmine_limited_visibility pull request #7
Opened 2021-02-18 10:10 UTC by mathieu-mbru

- ajout champ description pour les rôles fonctionnels
  - ajout description au survol sur le champ Visibility dans les formulaires
  - enrichissement des fichiers de langues, correction dans le code des valeurs codés en dur par leur libéllé du fichier de langue
  - ajout de la modal popup d'info listant les rôles sur le projet en fonction du tracker du ticket
  - ajout de la modal popup d'info listant les rôles sur la page Ticket : Edit, New, et Show
  - Correction bug affichage : à la création d'un nouveau ticket, lorsque le projet enfant est choisi, l'information "membres impliqués" (involved members) n'est pas mis à jour au niveau de l'affichage
  - Enrichissement des tests

2021-02-18 11:28 UTC, nanego requested changes
Merci pour cette Pull Request.
Voici quelques éléments à prendre en compte avant de pouvoir intégrer cette évolution.

2021-02-18 11:28 UTC, nanego commented on app/overrides/projects/show.rb
> +                      :text          => override
Pas la peine d'utiliser une variable si le code n'est utilisé qu'une seule fois.
Ce sera plus lisible ainsi :
```
:text => %(<%= cont...
```

2021-02-18 11:28 UTC, nanego commented on app/views/projects/_tab_selection_by_default.html.erb
> +            <% @project.functions.sorted.all.each do |function| %>
`find_each` est plus performant. À utiliser à la place de `all.each` quand c'est possible.

2021-02-18 11:28 UTC, nanego commented on app/views/projects/_tab_silent_functions.html.erb
> +            if ProjectFunctionTracker.joins(:project_function).includes(:project_function).where("project_id = ?", @project.id).count > 0
La condition sera plus claire en utilisant une variable. Et cela permettra de ne pas exécuter 2 fois la requête.

2021-02-18 11:28 UTC, nanego commented on app/views/projects/_tab_silent_functions.html.erb
> +            if ProjectFunctionTracker.joins(:project_function).includes(:project_function).where("project_id = ?", @project.id).count > 0
Par ailleurs, je ne suis pas certain que cette vérification soit nécessaire.

2021-02-22 15:29 UTC, mathieu-mbru commented on spec/controllers/functions_controller_spec.rb
> +      end.to change(ProjectFunction, :count).by(-3)
C'est entendu et pris en compte

2021-02-22 15:29 UTC, mathieu-mbru commented on app/controllers/functions_controller.rb
> +      project.functions.clear
C'est entendu et pris en compte

2021-02-22 15:29 UTC, mathieu-mbru commented on app/models/function.rb
> +  end
Dans l'implémentation, cette méthode est nécessaire pour récupérer les rôles inactifs qui contiennent des membres afin de les afficher dans les modals (en rouge). La seule fonction available_functions_for ne nous permet pas de les récupérer.

2021-02-22 15:29 UTC, mathieu-mbru commented on app/overrides/projects/show.rb
> +                      :text          => override
C'est entendu et pris en compte

2021-02-22 15:29 UTC, mathieu-mbru commented on app/views/projects/_tab_selection_by_default.html.erb
> +            <% @project.functions.sorted.all.each do |function| %>
C'est entendu et pris en compte

2021-02-22 15:29 UTC, mathieu-mbru commented on app/views/projects/_tab_silent_functions.html.erb
> +            if ProjectFunctionTracker.joins(:project_function).includes(:project_function).where("project_id = ?", @project.id).count > 0
C'est entendu et pris en compte pour la variable.

Concernant le second point, il s'agit du commit suivant : Correction bug affichage lors de l'édition des rôles silencieux : lorsqu'un rôle est mis en silencieux, la BDD est mise à jour mais l'affichage ne l'est pas.

Cette vérification a été ajoutée afin de prendre en compte le cas lors de la création d'un nouveau projet : un bug d'affichage a été identifié lorsque l'on configure un rôle invisible (depuis l'onglet rôle silencieux), la BDD est mise à jour mais l'affichage ne l'est pas.

2021-02-22 15:43 UTC, nanego commented on app/models/function.rb
> +  end
J'ai bien vu ce qu'ajoute cette nouvelle méthode. Mais je ne pense pas qu'on souhaite afficher les rôles inactifs dans la modale.

2021-02-22 15:55 UTC, mathieu-mbru commented on app/models/function.rb
> +  end
Nous sommes bien en phase qu'il s'agit des rôles ci-dessous ? 
Sinon c'est une incompréhension de notre part, nous supprimons c'est entendu.

![image](https://user-images.githubusercontent.com/75627140/108733298-ab6e2580-752e-11eb-9818-14a59f6c91a4.png)

2021-02-22 16:07 UTC, nanego commented on app/models/function.rb
> +  end
Oui, c'est une incompréhension sur le besoin initial.
À discuter davantage dans le Portail Redmine.

2021-02-24 13:39 UTC, merged